#!/bin/zsh

# git fetch -p && git reset --hard && git checkout origin/master -b feature/ticket
BASE_COMMAND="git fetch -p && git reset --hard && git checkout origin/master -b"
case "${1}" in
    -f|--feature)
        BASE_COMMAND="${BASE_COMMAND} feature/$2"
        ;;
    -b|--bug)
        BASE_COMMAND="${BASE_COMMAND} fix/$2"
        ;;
esac

eval "$BASE_COMMAND"

